### ISSUE TITLE
使用教程

### ISSUE THREAD

**Issue by junlintianxiawudi** [n9tank/rwTool#5]
您好，作者，请问有使用教程吗，谢谢

**Comment by n9tank** [comment]
并没有详细的使用教程，这只是一个后端程序。
在UiHandler DefaultRunTask()是默认输入实现，你只需要选择文件和模式，它会自动工作。
请格外注意，由于使用了SAF访问，部分厂商阉割了SAF的功能你可能需要提供其他文件管理器访问。
如使用MT管理器的打开方式，以及通过分享文件作为输入。
此外由于Android对权限的收紧，Android/data目录无法访问。
至于一些可变动的配置在README.MD给出了。

**Comment by junlintianxiawudi** [comment]
谢谢您的帮助
